apiVersion: 1

datasources:
  - name: MLflow PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: mlflow_db
    user: mlflow
    secureJsonData:
      password: mlflow123
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: true
